### ISSUE TITLE
extending ekman.m to use wind stress directly rather than calling windstress to compute it

### ISSUE THREAD

**Issue by uturuncoglu** [chadagreene/CDT#18]
It would be nice to add an option to ekman.m to use directly provided wind stress rather than using its internal calculation through calling windstress() function. Anyway, this is just a feature request and I think it is fairly easy to implement.

**Comment by chadagreene** [comment]
@uturuncoglu That's a totally reasonable request, and if I could do it all over again, I'd write the `ekman` function to accept only wind stress, not wind speed as inputs. 

I'm sort of swamped with other projects right now, and I'm not sure if/when I'll find the time to make the changes you request. Rather than waiting for me, I recommend hacking the current `ekman` function to create your own version without the internal wind stress calculation.

**Comment by uturuncoglu** [comment]
@chadagreene No worries. It was just an idea for other users. BTW, i have already hacked the Matlab code to calculate the Ekman related properties. Thanks.
